// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "14b0c1e2-12c8-4340-b7b0-82667a711883";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSwitcheChange();

float current1;
float energy1;
float power1;
float voltage1;
CloudLight switche;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(current1, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(energy1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(power1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltage1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(switche, READWRITE, ON_CHANGE, onSwitcheChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
